### ISSUE TITLE
Errors in building GameSDK

### ISSUE THREAD

**Issue by DavidDeep** [hendrikp/Plugin_SDK#21]
Hello, when I add all commands to files in GameSDK, I can't build it. Using Visual Stufio 2012 Express and Cryengine 3.5.8 This is what command line say: 
![untitled](https://cloud.githubusercontent.com/assets/1372415/6068579/7c600472-ad7d-11e4-93f0-5d480e2fdea8.png)
Thanks for reply.

**Comment by hendrikp** [comment]
I'm gonna need to see the output window text whats the warning.

In general 3.5.8 works fine, I myself am using 3.6.14 atm.

**Comment by Xaver2k** [comment]
I have a similar problem when i tried to compile with VS2013
first there where missing all that is in
CRYENGINE_Build_PC_v3_5_8_2310_freesdk\Code\Plugin_SDK\inc

i copied the files manually to:
CRYENGINE_Build_PC_v3_5_8_2310_freesdk\Code\CryEngine\CryCommon

and now i get these errors:

error C2259: 'CFactory<AnimPoseModifier::CLookAtSimple>' : cannot instantiate abstract class (Game.cpp)	D:\CRYENGINE_Build_PC_v3_5_8_2310_freesdk\Code\CryEngine\CryAction\Animation\PoseModifier\LookAtSimple.h	25	1	CryGameSDK

Error	2	error C2259: 'CFactory<CIKTorsoAim>' : cannot instantiate abstract class (Game.cpp)	D:\CRYENGINE_Build_PC_v3_5_8_2310_freesdk\Code\CryEngine\CryAction\Animation\PoseModifier\IKTorsoAim.h	16	1	CryGameSDK


any idea what could be the problem ?

**Comment by Xaver2k** [comment]
this is the code from the output window:

1>------ Skipped Build: Project: CryAction, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: CryGameSDK, Configuration: Debug x64 ------
2>  Game.cpp
2>D:\CRYENGINE_Build_PC_v3_5_8_2310_freesdk\Code\CryEngine\CryAction\Animation/PoseModifier/LookAtSimple.h(25): error C2259: 'CFactory<AnimPoseModifier::CLookAtSimple>' : cannot instantiate abstract class
2>          due to following members:
2>          'const char *ICryFactory::GetClassName(void) const' : is abstract
2>          d:\cryengine_build_pc_v3_5_8_2310_freesdk\code\cryengine\crycommon\cryextension\ICryFactory.h(28) : see declaration of 'ICryFactory::GetClassName'
2>D:\CRYENGINE_Build_PC_v3_5_8_2310_freesdk\Code\CryEngine\CryAction\Animation/PoseModifier/IKTorsoAim.h(16): error C2259: 'CFactory<CIKTorsoAim>' : cannot instantiate abstract class
2>          due to following members:
2>          'const char *ICryFactory::GetClassName(void) const' : is abstract
2>          d:\cryengine_build_pc_v3_5_8_2310_freesdk\code\cryengine\crycommon\cryextension\ICryFactory.h(28) : see declaration of 'ICryFactory::GetClassName'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========

**Comment by hendrikp** [comment]
Replacing CryCommon files is wrong, you didn't follow the integration guide.

**Comment by SalahAdDin** [comment]
Are Hendrikp updating this repo now?
