### ISSUE TITLE
Compatibilitie with VS 2015 and CryEngine V

### ISSUE THREAD

**Issue by SalahAdDin** [hendrikp/Plugin_SDK#24]
Hi @hendrikp, as we have now CryEngine V i'm triyin work in a new PlugIN, but i can't create the plugin:
I have the Plugin_SDK in this folder:
![directorio](https://cloud.githubusercontent.com/assets/5034215/13893956/e97aceea-ed30-11e5-82ef-fc48b293cfc6.jpg)
I set the new plugin project this:
![meleeplugin](https://cloud.githubusercontent.com/assets/5034215/13893959/f97e2508-ed30-11e5-8289-2893961780f0.jpg)
And i get this problem:
![error](https://cloud.githubusercontent.com/assets/5034215/13893962/035bd75a-ed31-11e5-81fe-511ffcd11489.jpg)

So, what's the problem?

I edit the `vsz` file to this:
```
VSWIZARD 7.0
Wizard=VsWizard.VsWizardEngine.13.0

Param="WIZARD_NAME = PluginWizard"
Param="ABSOLUTE_PATH = E:\Programas\Desarrollo\Crytek\CRYENGINE Launcher\Crytek\CRYENGINE_5.0\Code\Plugin_SDK\wizard\vc13"
Param="FALLBACK_LCID = 1033"
```

Both, the `Documents\Visual Studio 2015\...` as `E:\Programas\Desarrollo\Crytek\CRYENGINE Launcher\Crytek\CRYENGINE_5.0\Code\Plugin_SDK\wizard\vc13` files also.

What's the problem?

**Comment by hendrikp** [comment]
Hi,

most of the time the issue is with the folders
I would recommend you to install using an older plugin_sdk version from
bintray, after that change the folders to the vc13 one and copy the files
the installers created there.
E:\Programas\Desarrollo\Crytek\CRYENGINE Launcher\Crytek\CRYENGINE_5.0\
Code\Plugin_SDK\wizard\vc13

You could also instead just take an existing plugin and rename the
files/folders etc.
(Or you could run the wizard in an older version and just migrate it)

Regards Hendrik

2016-03-18 23:46 GMT+01:00 Yusuf (Josè) Luis <notifications@github.com>:

**Comment by SalahAdDin** [comment]
Ok, i install this wizar manually, i hadn't try with the installer. I'll go it.

**Comment by hendrikp** [comment]
Yes just press accept. (As i said after installation you still have to fix things)
